### ISSUE TITLE
How to install on Fedora 38

### ISSUE THREAD

**Issue by SebChaumont** [lkiesow/audiobookshelf-rpm#4]
Hello, 

I'm trying to install ABS on Fedora 38 and for some reasons I get this error message trying to run the dnf install command 

![image](https://github.com/lkiesow/audiobookshelf-rpm/assets/18669654/17ee73ec-551b-4231-9ea2-3f221ac71f46)

Any pointers as to why this is throwing me this error?

thanks a lot!

**Comment by lkiesow** [comment]
As the first section of the readme states:

> Supported operating systems are all Red Hat and CentOS Stream 8/9 variants.

Fedora is no el8/9 variant. It may still work installing the RPMs manually, but you won't get any auto-updates.
